# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.LDAindex <- function(origclass, origdata, proj = matrix(0), weight = TRUE) {
    .Call('PPtreeViz_LDAindex', PACKAGE = 'PPtreeViz', origclass, origdata, proj, weight)
}

.PDAindex <- function(origclass, origdata, proj = matrix(0), weight = TRUE, lambda = 0.1) {
    .Call('PPtreeViz_PDAindex', PACKAGE = 'PPtreeViz', origclass, origdata, proj, weight, lambda)
}

.Lrindex <- function(origclass, origdata, proj = matrix(0), weight = TRUE, r = 1L) {
    .Call('PPtreeViz_Lrindex', PACKAGE = 'PPtreeViz', origclass, origdata, proj, weight, r)
}

.GINIindex1D <- function(origclass, origdata, proj = numeric(0)) {
    .Call('PPtreeViz_GINIindex1D', PACKAGE = 'PPtreeViz', origclass, origdata, proj)
}

.ENTROPYindex1D <- function(origclass, origdata, proj = numeric(0)) {
    .Call('PPtreeViz_ENTROPYindex1D', PACKAGE = 'PPtreeViz', origclass, origdata, proj)
}

.PPopt <- function(origclass, origdata, q = 1L, PPmethod = "LDA", weight = TRUE, r = 1L, lambda = 0.1, energy = 0, cooling = 0.999, TOL = 0.0001, maxiter = 50000L) {
    .Call('PPtreeViz_PPopt', PACKAGE = 'PPtreeViz', origclass, origdata, q, PPmethod, weight, r, lambda, energy, cooling, TOL, maxiter)
}

