# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

NormalizeD <- function(rawdata) {
    .Call('PPtreeViz_NormalizeD', PACKAGE = 'PPtreeViz', rawdata)
}

NormalizeProjV <- function(proj) {
    .Call('PPtreeViz_NormalizeProjV', PACKAGE = 'PPtreeViz', proj)
}

NormalizeProjV1 <- function(proj) {
    .Call('PPtreeViz_NormalizeProjV1', PACKAGE = 'PPtreeViz', proj)
}

FindMaxID <- function(X) {
    .Call('PPtreeViz_FindMaxID', PACKAGE = 'PPtreeViz', X)
}

LDAindex1 <- function(projclass, projdata) {
    .Call('PPtreeViz_LDAindex1', PACKAGE = 'PPtreeViz', projclass, projdata)
}

LDAindex2 <- function(projclass, projdata) {
    .Call('PPtreeViz_LDAindex2', PACKAGE = 'PPtreeViz', projclass, projdata)
}

Lpindex1 <- function(projclass, projdata, r) {
    .Call('PPtreeViz_Lpindex1', PACKAGE = 'PPtreeViz', projclass, projdata, r)
}

Lpindex2 <- function(projclass, projdata, r) {
    .Call('PPtreeViz_Lpindex2', PACKAGE = 'PPtreeViz', projclass, projdata, r)
}

PDAindex1 <- function(projclass, projdata, lambda) {
    .Call('PPtreeViz_PDAindex1', PACKAGE = 'PPtreeViz', projclass, projdata, lambda)
}

PDAindex2 <- function(projclass, projdata, lambda) {
    .Call('PPtreeViz_PDAindex2', PACKAGE = 'PPtreeViz', projclass, projdata, lambda)
}

GINIindex1D <- function(projclass, projdata) {
    .Call('PPtreeViz_GINIindex1D', PACKAGE = 'PPtreeViz', projclass, projdata)
}

ENTROPYindex1D <- function(projclass, projdata) {
    .Call('PPtreeViz_ENTROPYindex1D', PACKAGE = 'PPtreeViz', projclass, projdata)
}

PPoptimizeqD <- function(origclass, origdata, method, q, r = 1L, lambda = 0, TOL = 0.00001, maxiter = 5000L) {
    .Call('PPtreeViz_PPoptimizeqD', PACKAGE = 'PPtreeViz', origclass, origdata, method, q, r, lambda, TOL, maxiter)
}

PPoptimizeAnnealqD <- function(origclass, origdata, method, q, r = 1L, lambda = 0, TOL = 0.0001, maxiter = 50000L, energy = 0.01, cooling = 0.999) {
    .Call('PPtreeViz_PPoptimizeAnnealqD', PACKAGE = 'PPtreeViz', origclass, origdata, method, q, r, lambda, TOL, maxiter, energy, cooling)
}

PPoptimizeAnnealorig <- function(origclass, origdata, method, q, r = 1L, lambda = 0, TOL = 0.0001, maxiter = 50000L, energy = 0.01, cooling = 0.999, tempstart = 1) {
    .Call('PPtreeViz_PPoptimizeAnnealorig', PACKAGE = 'PPtreeViz', origclass, origdata, method, q, r, lambda, TOL, maxiter, energy, cooling, tempstart)
}

